name: CI Workflow

on: [pull_request]

env:
  RUNS_ON: ubuntu-latest
  NODE_VERSION: 20.18.0

jobs:
  lint:
    name: Lint
    runs-on: ${{ env.RUNS_ON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node dependencies
        run: npm ci

      - name: Run linters action
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          tsc: true